[package]
name = "polyglot"
version = "0.1.0"
authors = ["Ricardo Almeida <ricardoluiz1.almeida@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
radix_fmt = "1"