name: Deno

on:
  push:
    branches: [master]
    paths-ignore:
      - "*.md"
      - ".dockerignore"
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-16.04

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Run Tests
        run: cd deno && deno test -A --unstable
