name: Rust

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "*.md"
      - ".dockerignore"
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd rust && cargo build --verbose
    - name: Run tests
      run: cd rust && cargo test --verbose
